#spring.application.name=cpu-utilization
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    data-locations: classpath:dummyData.sql
    initialization-mode: always

  sql:
    init:
      data-locations: classpath*:dummyData.sql
      mode: always
      platform: h2

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
